// <auto-generated />
using InvoiceGenAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InvoiceGenAPI.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220320130916_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("InvoiceGenAPI.Entities.PaymentGateway", b =>
                {
                    b.Property<int>("PaymentGatewayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Additional_field")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Configured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gateway_name")
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentGatewayId");

                    b.ToTable("Paymentgateway");
                });
#pragma warning restore 612, 618
        }
    }
}
